name: 'Setup GraalVM environment'
description: 'Setup your runner with GraalVM built by Gluon'
author: 'DeLaGuardo'
branding:
  icon: 'gift'
  color: 'blue'
inputs:
  graalvm:
    description: 'The GraalVM version built by Gluon, defaults to latest'
    default: 'latest'
  jdk:
    description: 'The JDK version used to build the GraalVM version. Possible values: java23 (default), java17 or java11, if GraalVM is 22+. For lower, it should be empty'
    default: 'java23'
  arch:
    description: 'Architecture flag. Possible values: x86_64 (default) and aarch64. The latter is available for M1 runners and GraalVM 22.1+'
    default: 'x86_64'
runs:
  using: 'node20'
  main: 'dist/index.js'
